#+TITLE: 2021，小结
#+SETUPFILE: ../tpls/tpl.org
#+DATE: <2022-01-23 Sun>

元旦将近的时候就想着花一点时间回顾下过去的 2021 年，可真到点了又刻意不再想这件事。大概是太久没有动笔，也就少了提笔的勇气了。年终小结已经坚持了很多年，最初的时候我们「[[http://www.zhangjiee.com/blog/index.html][Jerry]]、[[https://blog.tankywoo.com/][Tanky]] 和我」几个各自写着，后来每到一年年底的时候会彼此催稿，今年大家就像商量好一样不再提年终总结了。一年又一年，经历的事情越来越多，内心却慢慢变得淡然，少了些挣扎。2021 年结束的时候我试探性的问了下 Jerry 要不写个小结，回答写的一些东西不适合对外公开，博客以后也会关闭。Tanky 我是问也没问，这家伙现在压根就不在群里说话了，此刻或许正在盘着他的那串珠子呢。

上周 Jerry 在群又提了下，年终小结今年这是全军覆没了。我是没想着不写的，只是一直拖着，想着拖到我想写的时候自然就会写。可是也不能一直拖着，再拖一周就春节了。前天把博客的域名续了一年，这个域名也跟了我好些年了，写或者不写，留着有个牵挂也好。今天刚好得空，想着还是把这个作业交了吧。


** 关于工作

2021 年换了份工作，至于换工作的原因去年的年终小结已经提过。上家公司是我工作的几家公司中，唯一一个不是我自己发起离职请求的，现在想来还挺喜剧的。和前老板表达离职的诉求几个月前就说过了，老板的意思是等年后再提。当时的情况是这样的，老板和我聊完绩效之后，让我确认下明天新公司是否可以入职，如果可以我今天可以发起离职申请了。因为时间确实很短，当天发起离职申请系统时间上已经不允许了，直接找 HRG 系统发起的。前公司办理离职的行政同事开玩笑说，前老板真好，合着马上春节了，给公司省钱了。于是，赶在除夕的前一天，入职了现在的这家公司。

再过几天新公司也快满一年了，这份工作比之前的工作都要忙碌。从 [[https://github.com/opskumu/issues/issues/29][学习周报「2021」]] 就可以看出来，基本去了新公司之后就断更了。上份工作的时候，自己可支配的时间比较多，意味着留给自己胡思乱想的时间就很多。而这份工作恰好相反，根本就不会给你思考的时间，有点时间就只想躺着休息放空了。那是否会后悔换工作呢，只能说有得有失，后悔是谈不上的。一份工作做久了，很难绕过机械化。换了个新公司只会带来几个月的新鲜期，新鲜期一过你就要面对各种杂事。只能说现在公司体量大一点，人那么多事情自然就不会少。不过不管怎么说，换工作还是意味着自己想做一些改变。回顾过去的一年，要说个人的成长技术上来说是偏少的，从其他方面来说提升的也不多。有时候会感慨是不是因为工作越久，越往后成长的就会越少。和年龄多少有些关系，包括精力这些都会有些分散。不过仔细一想倒不全是，工作年限长了之后，自己很容易给自己设限，包括知识体系这些，容易经验主义。这是件挺可怕的事情，关键有时候自己又不一定感知的到。

我偶尔还会反问自己，现在的工作除了谋生以外，是否还有其它的意义。刚毕业那会就不会想这些问题，那时候对一切未知的事物充满好奇。会加入各种技术群组，会提问，也会热情的帮别人解决问题。遇到技术难题的时候，会兴奋，会寻找各种解决问题的方法。而现在，虽然遇到问题了也会去解决，但多少少了许多乐趣，解决之后可能只是疲惫，而并非那会的快乐和满足感。另外则是提到的工作焦虑，互联网圈经常调侃 35+ 失业，有时候自己也会自嘲已到 35+ 的边缘，后面何去何从呢。作为一个技术人，好像也只会做技术相关的，真如果失业了也确实不知如何。不过，话又说回来了，想这些有的没的，也并不会带来什么帮助。唯一能做的就是好好工作，能进步一点就一点。毕竟工作也不是全部，该来的总会来，做好自己就好了。


** 关于生活

「工作当然并不是全部，生活才是。」觉得这句话倒是挺酷的，不过生活还得要靠工作来维系。说简单点，对大部分人来说工作就是赚钱养家，好好生活。

2021 年，对我来说好像是一个大年，很多大家常说的人生大事都是在这一年发生的。先是在杭州买了房，我爸妈常说买房是大事，我也知道是个大事，不过真到了这一天到来的时候，好像也就那么回事。仍然记得，之前在上海工作的时候，有天坐在行驶在高架桥的出租车上，看着车窗外的万家灯火，想着什么时候能在这些灯火中有间属于于自己的一方天地就好了。转眼多年，我也从上海来到了杭州，在杭州安了家。和媳妇是 2020 年在老家举办的婚礼，当时没有直接领证，2021 年 9 月 9 号我们在西湖民政局登记结婚，成为合法夫妻。还有就是媳妇怀孕了，我们的宝宝将在虎年出生，虽然现在还没有完全做好当父亲的准备，2022 年目标就是朝着着成为一个合格的奶爸努力。

今年游玩是这些年最少的一次，除了 21 年元旦的东北之行，21 年基本没怎么出过杭州。倒是因为出差的机会，逛了一次故宫，算是弥补了之前在北京工作那会没有去过故宫的遗憾。往年的时候，即使不出远门，也会不定期的去爬西湖群山，今年是彻底歇菜了，连出去跑步都懒得走半步。一部分是工作原因吧，换工作之后一到周末就想躺着，哪儿也不想去。这不，年底体检的时候，发现脂肪肝都找上我了。除了这，体重也是达到历史新高，比换工作前胖了 10 斤多。游玩可以没有，运动想来是必不可少的，2022 还得加强体育锻炼，再不能只动动嘴皮子了，身体要是不好，哪能做好奶爸呢。

2021 除了体重达到了历史新高，读书也达到了历史新低，总共读过的书十本都不到。其实不是没时间读书，而是闲暇之时也很难静下心来去阅读。最近又尝试着让自己去阅读了，当静下心去阅读的时候，就是享受的时刻。

前面提到了体检，想到这里，2022 要把父母的每年的体检要重视起来。我媳妇这点做的好多了，每年都会把老人家的体检安排妥当。我在这方面做的就很不好，有时候想起来了就催一下父母，父母本身也没有体检的习惯，大部分都不了了之。父母体检的事情要重视起来，父母年纪大了，定期体检很重要，身边也有很多案例，健康的事情是马虎不得的。

** 再见 2021

最后，你好 2022。再见，2021。

