#+SETUPFILE: ../tpls/tpl.org
#+TITLE: 2019，小结
#+DATE: <2020-01-02 Tue>

2019 年，对我来说，发生的事情有点多，有些历历在目，有些已变得模糊。

** 关于工作

最近偶尔会想自己过往的经历，当初为何选择这一行，又怎么走到今天。历程不算艰辛，也不曾遇到什么大的挫折，想来还觉得太过平坦。如果算上长沙的那份工作，现在这份工作是第五份。2016 年来到现在公司的时候，不曾想一溜烟就是三年，这是至今职业生涯工作最长的一家公司了。当初选择这家公司并没有多想，觉得聊的还不错，有一定的发展空间就来了。对于公司所在的行业是没有过多了解，于是就误打误撞赶上了互联网金融的这波浪潮，接着就是亲历这个行业的沉浮。行业或者公司本身，对于一线技术人员来说能够左右的太少了，能做的就是利用技术本身带来最大的效益。 

对于技术和业务，也许是运维出身的原因吧，个人一直以来的观点都是业务驱动技术。脱离了业务谈技术，多少有些空谈。2019 年因为大环境的原因，公司整体的业务进展的并不顺利，因此我所负责的容器平台支撑业务量并没有什么质的提升。这一年主要的工作一是内部的私有化云平台的建设，另外一个就是容器平台相关的生态完善。年中的时候，因为人员流动和业务需要，内部的两个小组合并成了云平台小组，从之前两个人的小作坊，变成了 6 人的小团队。回顾这一年，自己的技术能力并没有一个大的提升，而管理能力与其说弱，缺失可能更为恰当。其实没有提升的原因说来也简单，归根结底还是自身。技术来说在自己的舒适圈太长时间了，还有些松懈，并没有主动尝试去突破。而管理来说还是角色没有很好的转换，大多数时候是站在个人而非团队角度来思考和决策，没有承担这个角色应有的责任。

年底的时候出去面了几轮，结果都不太理想，和自己预期差不太多。面稍微和开发沾点边的岗位，基本都会涉及到算法相关的笔试题，而我数据结构和算法这块的理论都是缺失的，所以相关岗位不用想也不会好。以前还会疑惑，想着算法这些能有什么用，实际上工作中大部分场景也不会涉及，真要遇到了现查现学也不会花费多长时间。碰壁几次之后倒不再疑惑了，每个人都有自身衡量候选人的标准。短短的 1 个小时的面试中怎么筛选出需要的人，无非一方面是技术能力，包括前面说的数据结构和算法基本功，然后就是业务能力和个人其他的一些考量，而技术能力这块又是最容易量化的点。再者来说，数据结构和算法是编程的基础，以后个人技术发展的高度还是很受这些知识限制的。

我已经工作七年多了，对个人的技术和业务能力这块当然是自信的，可对自己的技术短板也有一个清醒的认识。数据结构和算法这块的理论，我从一入行的时候，就知道这块是自己所欠缺的，七年以后依然没有把这一块给补起来，无论怎么解释都是说不过去。非科班？工作中不需要？这种搪塞的理由，说出来自己也恶心。2019 年已经过去，2020 年会把这些欠缺的一一捡起来。

** TODO 关于生活
